### PR TITLE
Lock guava to 20.0

### PR DESCRIPTION
**Pull request by carlossg**
Otherwise 21.0 causes
`java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;`

Broken with #62

### CODE REVIEW

**Comment by jglick** [comment]
I suspect what you meant to do was to use an `<exclusion>` of `guava` from `io.findify:s3mock_2.12`…?

**Comment by jglick** [comment]
cf. #44

**Comment by jglick** [comment]
It is just that we care a lot about jclouds and the AWS SDK being bundled with a preferred version of Guava; and not at all about S3Mock getting a particular version—either the tests pass or they do not. Using `exclusion` assures us that the version is picked up from the right place even if we update the libs being used at runtime.
